'File:         FX3I2C.vb
'Author:       Alex Nolan (alex.nolan@analog.com)
'Date:         5/13/2020
'Description:  I2C interfacing for the FX3

''' <summary>
''' I2C pre-amble class.
''' </summary>
Public Class I2CPreamble

    'private members
    Dim m_addr As Byte
    Dim m_stopMask As Byte
    Dim m_startMask As Byte

    ''' <summary>
    ''' I2C Preamble constructor. Initializes all fields to zero
    ''' </summary>
    Public Sub New()
        PreambleData = New List(Of Byte)
        m_addr = 0
        m_stopMask = 0
        m_startMask = 0
    End Sub

    ''' <summary>
    ''' The bytes to transmit following the device address and R/W bit.
    ''' The maximum size of this list is 7 bytes, giving 8 total bytes 
    ''' transmitted as part of the pre-amble.
    ''' </summary>
    Public PreambleData As List(Of Byte)

    ''' <summary>
    ''' This is the 7-bit slave address for the device to access on the I2C bus.
    ''' The address value must be left justified, with a zero in the least significant
    ''' bit. The address bits (starting at DeviceAddress bit 7) are the first data transmitted
    ''' by the FX3 when starting an I2C transaction. A R/W bit (generated by the firmware)
    ''' follows the seven device address bits to complete the first byte.
    ''' </summary>
    ''' <returns></returns>
    Public Property DeviceAddress As Byte
        Get
            Return m_addr
        End Get
        Set(value As Byte)
            'clear bit 0
            m_addr = CByte(value And &HFEUI)
        End Set
    End Property

    ''' <summary>
    ''' This field controls the stop condition sent after every byte of preamble
    ''' data. The device address is the first byte of data, following by up to 
    ''' seven additional bytes in PreAmbleData. For example, setting StopMask to
    ''' 0x01 will cause a stop condition to be generated after sending DeviceAddress, while
    ''' setting StopMask to 0x02 will cause a stop condition to be generated after 
    ''' sending PreambleData[0], and so on. Note, setting a bit in StopMask will cause 
    ''' the corresponding bit in StartMask to be cleared, if it is also set.
    ''' </summary>
    ''' <returns>The 8 bit preamble stop mask</returns>
    Public Property StopMask As Byte
        Get
            Return m_stopMask
        End Get
        Set(value As Byte)
            m_stopMask = value
            m_startMask = m_startMask And (Not m_stopMask)
        End Set
    End Property

    ''' <summary>
    ''' This field controls the start condition sent after every byte of preamble
    ''' data. The device address is the first byte of data, following by up to 
    ''' seven additional bytes in PreAmbleData. For example, setting StartMask to
    ''' 0x04 will cause a start condition to be generated after sending PreambleData[1], while
    ''' setting StartMask to 0x08 will cause a start condition to be generated after 
    ''' sending PreambleData[2], and so on. Note, setting a bit in StartMask will cause 
    ''' the corresponding bit in StopMask to be cleared, if it is also set.
    ''' </summary>
    ''' <returns>The 8 bit preamble start mask</returns>
    Public Property StartMask As Byte
        Get
            Return m_startMask
        End Get
        Set(value As Byte)
            m_startMask = value
            m_stopMask = m_stopMask And (Not m_startMask)
        End Set
    End Property

    ''' <summary>
    ''' Helper function to serialize an I2C preamble. Puts the 
    ''' preamble into a byte array which can be sent over USB
    ''' </summary>
    ''' <returns>Byte array containing the pre-amble</returns>
    Friend Function Serialize() As IEnumerable(Of Byte)

        'data array
        Dim data As New List(Of Byte)

        'preamble count
        Dim count As Integer

        'pre-amble length in first byte
        count = PreambleData.Count + 1
        'clamp at 8 bytes
        If count > 8 Then count = 8
        data.Add(CByte(count))

        'ctrl lower (start mask)
        data.Add(StartMask)

        'ctrl upper (stop mask)
        data.Add(StopMask)

        'dev addr
        data.Add(DeviceAddress)

        'pre-amble data
        If PreambleData.Count > 7 Then
            PreambleData.RemoveRange(7, PreambleData.Count - 7)
        End If
        data.AddRange(PreambleData)

        Return data

    End Function

End Class

Partial Class FX3Connection

    ''' <summary>
    ''' Get/Set the FX3 I2C bit rate. Valid range 100KHz - 1MHz. Defaults to 100KHz
    ''' </summary>
    ''' <returns>Current I2C bit rate setting</returns>
    Public Property I2CBitRate As UInteger
        Get
            Return m_i2cbitrate
        End Get
        Set(value As UInteger)
            'valid range 100KHz - 1MHz
            If value < 100000 Then Throw New FX3ConfigurationException("ERROR: Invalid I2C bit rate. Must be at least 100KHz")
            If value > 1000000 Then Throw New FX3ConfigurationException("ERROR: Invalid I2C bit rate. Must be at 1MHz or less")

            'send command to update FX3 I2C config
            SetI2CBitRate(value)

            'save setting
            m_i2cbitrate = value
        End Set
    End Property

    ''' <summary>
    ''' Read bytes from an I2C slave device attached to the FX3.
    ''' </summary>
    ''' <param name="Preamble">The I2C preamble to transmit at the start of the read operation</param>
    ''' <param name="NumBytes">The number of bytes to read over I2C after sending the preamble</param>
    ''' <param name="TimeoutInMs">Read timeout period, in ms</param>
    ''' <returns>The data read from the I2C slave device</returns>
    Public Function I2CReadBytes(Preamble As I2CPreamble, NumBytes As UInteger, TimeoutInMs As UInteger) As Byte()

        'check inputs

        'send I2C read command over control endpoint

        'get data back from bulk endpoint (in 512 byte chunks)

    End Function

    ''' <summary>
    ''' Write bytes to an I2C slave device attached to the FX3
    ''' </summary>
    ''' <param name="Preamble">The I2C preamble to transmit at the start of the write operation</param>
    ''' <param name="WriteData">The write data to transmit on SDA after finishing the preamble</param>
    ''' <param name="TimeoutInMs">Write timeout period, in ms</param>
    Public Sub I2CWriteBytes(Preamble As I2CPreamble, WriteData As IEnumerable(Of Byte), TimeoutInMs As UInteger)

        'check inputs

        'send I2C write command + data over control endpoint

    End Sub


    ''' <summary>
    ''' Helper function to set i2c bit rate on FX3
    ''' </summary>
    ''' <param name="BitRate">Bit rate setting</param>
    Private Sub SetI2CBitRate(BitRate As UInteger)

        'send command

        'check return status

    End Sub

End Class
