'File:         FX3I2C.vb
'Author:       Alex Nolan (alex.nolan@analog.com)
'Date:         5/13/2020
'Description:  I2C interfacing for the FX3

''' <summary>
''' I2C pre-amble class.
''' </summary>
Public Class I2CPreamble

    'private members
    Dim m_addr As Byte
    Dim m_stopMask As Byte
    Dim m_startMask As Byte

    ''' <summary>
    ''' I2C Preamble constructor. Initializes all fields to zero
    ''' </summary>
    Public Sub New()
        PreambleData = New List(Of Byte)
        m_addr = 0
        m_stopMask = 0
        m_startMask = 0
    End Sub

    ''' <summary>
    ''' The bytes to transmit following the device address and R/W bit.
    ''' The maximum size of this list is 7 bytes, giving 8 total bytes 
    ''' transmitted as part of the pre-amble.
    ''' </summary>
    Public PreambleData As List(Of Byte)

    ''' <summary>
    ''' This is the 7-bit slave address for the device to access on the I2C bus.
    ''' The address value must be left justified, with a zero in the least significant
    ''' bit. The address bits (starting at DeviceAddress bit 7) are the first data transmitted
    ''' by the FX3 when starting an I2C transaction. A R/W bit (generated by the firmware)
    ''' follows the seven device address bits to complete the first byte.
    ''' </summary>
    ''' <returns></returns>
    Public Property DeviceAddress As Byte
        Get
            Return m_addr
        End Get
        Set(value As Byte)
            'clear bit 0
            m_addr = CByte(value And &HFEUI)
        End Set
    End Property

    ''' <summary>
    ''' This field controls the stop condition sent after every byte of preamble
    ''' data. The device address is the first byte of data, following by up to 
    ''' seven additional bytes in PreAmbleData. For example, setting StopMask to
    ''' 0x01 will cause a stop condition to be generated after sending DeviceAddress, while
    ''' setting StopMask to 0x02 will cause a stop condition to be generated after 
    ''' sending PreambleData[0], and so on. Note, setting a bit in StopMask will cause 
    ''' the corresponding bit in StartMask to be cleared, if it is also set.
    ''' </summary>
    ''' <returns>The 8 bit preamble stop mask</returns>
    Public Property StopMask As Byte
        Get
            Return m_stopMask
        End Get
        Set(value As Byte)
            m_stopMask = value
            m_startMask = m_startMask And (Not m_stopMask)
        End Set
    End Property

    ''' <summary>
    ''' This field controls the start condition sent after every byte of preamble
    ''' data. The device address is the first byte of data, following by up to 
    ''' seven additional bytes in PreAmbleData. For example, setting StartMask to
    ''' 0x04 will cause a start condition to be generated after sending PreambleData[1], while
    ''' setting StartMask to 0x08 will cause a start condition to be generated after 
    ''' sending PreambleData[2], and so on. Note, setting a bit in StartMask will cause 
    ''' the corresponding bit in StopMask to be cleared, if it is also set.
    ''' </summary>
    ''' <returns>The 8 bit preamble start mask</returns>
    Public Property StartMask As Byte
        Get
            Return m_startMask
        End Get
        Set(value As Byte)
            m_startMask = value
            m_stopMask = m_stopMask And (Not m_startMask)
        End Set
    End Property

    ''' <summary>
    ''' Helper function to serialize an I2C preamble. Puts the 
    ''' preamble into a byte array which can be sent over USB
    ''' </summary>
    ''' <returns>Byte array containing the pre-amble</returns>
    Friend Function Serialize() As IEnumerable(Of Byte)

        'data array
        Dim data As New List(Of Byte)

        'preamble count
        Dim count As Integer

        'pre-amble length in first byte
        count = PreambleData.Count + 1
        'clamp at 8 bytes
        If count > 8 Then count = 8
        data.Add(CByte(count))

        'ctrl lower (start mask)
        data.Add(StartMask)

        'ctrl upper (stop mask)
        data.Add(StopMask)

        'dev addr
        data.Add(DeviceAddress)

        'pre-amble data
        If PreambleData.Count > 7 Then
            PreambleData.RemoveRange(7, PreambleData.Count - 7)
        End If
        data.AddRange(PreambleData)

        Return data

    End Function

End Class

Partial Class FX3Connection

    ''' <summary>
    ''' Get/Set the FX3 I2C bit rate. Valid range 100KHz - 1MHz. Defaults to 100KHz
    ''' </summary>
    ''' <returns>Current I2C bit rate setting</returns>
    Public Property I2CBitRate As UInteger
        Get
            Return m_i2cbitrate
        End Get
        Set(value As UInteger)
            'valid range 100KHz - 1MHz
            If value < 100000 Then Throw New FX3ConfigurationException("ERROR: Invalid I2C bit rate. Must be at least 100KHz")
            If value > 1000000 Then Throw New FX3ConfigurationException("ERROR: Invalid I2C bit rate. Must be at 1MHz or less")

            'send command to update FX3 I2C config
            SetI2CBitRate(value)

            'save setting
            m_i2cbitrate = value
        End Set
    End Property

    ''' <summary>
    ''' Get/Set the FX3 I2C retry count. This is 
    ''' </summary>
    ''' <returns></returns>
    Public Property I2CRetryCount As UShort
        Get
            Return m_i2cRetryCount
        End Get
        Set(value As UShort)
            'send command to update FX3 I2C config
            SetI2CRetryCount(value)

            'save setting
            m_i2cRetryCount = value
        End Set
    End Property



    ''' <summary>
    ''' Read bytes from an I2C slave device attached to the FX3.
    ''' </summary>
    ''' <param name="Preamble">The I2C preamble to transmit at the start of the read operation</param>
    ''' <param name="NumBytes">The number of bytes to read over I2C after sending the preamble</param>
    ''' <param name="TimeoutInMs">Read timeout period, in ms</param>
    ''' <returns>The data read from the I2C slave device</returns>
    Public Function I2CReadBytes(Preamble As I2CPreamble, NumBytes As UInteger, TimeoutInMs As UInteger) As Byte()

        'transfer buffer
        Dim buf As New List(Of Byte)

        'status buffer
        Dim bulkBuf(511) As Byte

        'transfer size
        Dim transferSize As Integer

        'track if operation is done
        Dim transferDone, validTransfer As Boolean

        'track timeout
        Dim timer As New Stopwatch

        'num read bytes first (0 - 3)
        buf.Add(CByte(NumBytes And &HFFUI))
        buf.Add(CByte((NumBytes >> 8) And &HFFUI))
        buf.Add(CByte((NumBytes >> 16) And &HFFUI))
        buf.Add(CByte((NumBytes >> 24) And &HFFUI))

        'timeout (4 - 7)
        buf.Add(CByte(TimeoutInMs And &HFFUI))
        buf.Add(CByte((TimeoutInMs >> 8) And &HFFUI))
        buf.Add(CByte((TimeoutInMs >> 16) And &HFFUI))
        buf.Add(CByte((TimeoutInMs >> 24) And &HFFUI))

        'pre-amble
        buf.AddRange(Preamble.Serialize())

        'send I2C read command over control endpoint
        ConfigureControlEndpoint(USBCommands.ADI_I2C_READ_BYTES, True)
        If Not XferControlData(buf.ToArray(), buf.Count, 2000) Then
            Throw New FX3CommunicationException("ERROR: Control endpoint transfer timed out while starting I2C read command")
        End If

        'accumulate data over bulk endpoint
        transferDone = False
        buf.Clear()
        timer.Start()
        While (Not transferDone) And (timer.ElapsedMilliseconds < TimeoutInMs)
            'check if done
            If buf.Count >= NumBytes Then
                transferDone = True
            Else
                'get a block of data from bulk in endpoint
                transferSize = CInt(Math.Min(512, NumBytes - buf.Count))
                'transfer will run in 512 byte blocks until last transfer, which cleans up remaining data
                validTransfer = FX3USB.USB.XferData(bulkBuf, transferSize, DataInEndPt)
                If validTransfer Then
                    'add all the data received
                    For i As Integer = 0 To transferSize - 1
                        buf.Add(bulkBuf(i))
                    Next
                End If
            End If
        End While

        'check timeout
        If Not transferDone Then
            Throw New FX3CommunicationException("ERROR: I2C read timed out. Timeout period " + TimeoutInMs.ToString() + "ms")
        End If

        Return buf.ToArray()

    End Function

    ''' <summary>
    ''' Write bytes to an I2C slave device attached to the FX3
    ''' </summary>
    ''' <param name="Preamble">The I2C preamble to transmit at the start of the write operation</param>
    ''' <param name="WriteData">The write data to transmit on SDA after finishing the preamble</param>
    ''' <param name="TimeoutInMs">Write timeout period, in ms</param>
    Public Sub I2CWriteBytes(Preamble As I2CPreamble, WriteData As IEnumerable(Of Byte), TimeoutInMs As UInteger)

        'transfer buffer
        Dim buf As New List(Of Byte)

        'status buffer
        Dim statusBuf(3) As Byte

        'status
        Dim status As UInteger

        'track if operation is done
        Dim transferDone As Boolean

        'track timeout
        Dim timer As New Stopwatch

        'check that write data is less than (4096 - (11 + 4 + 4)) bytes
        If WriteData.Count > 4077 Then
            Throw New FX3ConfigurationException("ERROR: Invalid write data length. Cannot total command transfer size cannot be more than 4096 bytes")
        End If

        'write data length first (0 - 3)
        buf.Add(CByte(WriteData.Count And &HFFUI))
        buf.Add(CByte((WriteData.Count >> 8) And &HFFUI))
        buf.Add(CByte((WriteData.Count >> 16) And &HFFUI))
        buf.Add(CByte((WriteData.Count >> 24) And &HFFUI))

        'timeout (4 - 7)
        buf.Add(CByte(TimeoutInMs And &HFFUI))
        buf.Add(CByte((TimeoutInMs >> 8) And &HFFUI))
        buf.Add(CByte((TimeoutInMs >> 16) And &HFFUI))
        buf.Add(CByte((TimeoutInMs >> 24) And &HFFUI))

        'pre-amble
        buf.AddRange(Preamble.Serialize())

        'write data
        buf.AddRange(WriteData)

        'send I2C write command + data over control endpoint
        ConfigureControlEndpoint(USBCommands.ADI_I2C_WRITE_BYTES, True)
        If Not XferControlData(buf.ToArray(), buf.Count, 2000) Then
            Throw New FX3CommunicationException("ERROR: Control endpoint transfer timed out while starting I2C write command")
        End If

        'wait for done command from bulk endpoint
        transferDone = False
        timer.Start()
        While (Not transferDone) And (timer.ElapsedMilliseconds < TimeoutInMs)
            transferDone = FX3USB.USB.XferData(statusBuf, 4, DataInEndPt)
        End While

        'check timeout
        If Not transferDone Then
            Throw New FX3CommunicationException("ERROR: I2C write timed out. Timeout period " + TimeoutInMs.ToString() + "ms")
        End If

        'check status
        status = BitConverter.ToUInt32(statusBuf, 0)
        If status <> 0 Then
            Throw New FX3BadStatusException("ERROR: Bad status code after I2C write. Error code: 0x" + status.ToString("X4"))
        End If

    End Sub


    ''' <summary>
    ''' Helper function to set i2c bit rate on FX3
    ''' </summary>
    ''' <param name="BitRate">Bit rate setting</param>
    Private Sub SetI2CBitRate(BitRate As UInteger)

        'transfer buffer
        Dim buf(3) As Byte

        'status
        Dim status As UInteger

        'configure for i2c set bit rate command
        ConfigureControlEndpoint(USBCommands.ADI_I2C_SET_BIT_RATE, False)
        FX3ControlEndPt.Value = CUShort(BitRate And &HFFFFUI)
        FX3ControlEndPt.Index = CUShort((BitRate And &HFFFF0000UI) >> 16)

        'send command
        If Not XferControlData(buf, 4, 2000) Then
            Throw New FX3CommunicationException("ERROR: Control endpoint transfer timed out while setting I2C bit rate")
        End If

        'check status
        status = BitConverter.ToUInt32(buf, 0)
        If status <> 0 Then
            Throw New FX3BadStatusException("ERROR: Bad status code after setting I2C bit rate. Error code: 0x" + status.ToString("X4"))
        End If

    End Sub

    Private Sub SetI2CRetryCount(Count As UShort)

        'transfer buffer
        Dim buf(3) As Byte

        'status
        Dim status As UInteger

        'configure for i2c set bit rate command
        ConfigureControlEndpoint(USBCommands.ADI_I2C_RETRY_COUNT, False)
        FX3ControlEndPt.Value = Count

        'send command
        If Not XferControlData(buf, 4, 2000) Then
            Throw New FX3CommunicationException("ERROR: Control endpoint transfer timed out while setting I2C retry count")
        End If

        'check status
        status = BitConverter.ToUInt32(buf, 0)
        If status <> 0 Then
            Throw New FX3BadStatusException("ERROR: Bad status code after setting I2C retry count. Error code: 0x" + status.ToString("X4"))
        End If

    End Sub

End Class
